# SPDX-License-Identifier: AGPL-3.0-or-later
# Intake cluster client authentication (09 §10 Auth, DB-022, R7 SI-E-01). Installed as
# /etc/candor/intake/postgresql/pg_hba.conf (root:postgres 0640).
# 09 §10 + ADR-052(9): only three peer-authenticated logins over the Unix socket, each through
# its own pg_ident map and only to the tenant database(s): the store (candor-istore ->
# candor_istore), the maintenance jobs (candor-imaint -> candor_intake_maint, the database owner,
# never a member of the schema owner; AUD-RM2-STO-24, lead decision 2026-10-01)
# and `candorctl migrate` (candor-migrate -> candor_intake_migrator, the non-superuser schema
# owner). Everything else is rejected - including the postgres superuser. No superuser
# single-user mode for migrations (ADR-052(9)); bootstrap only, see SPEC-NOTES D-11.
# config-check.sh compares this file line by line with its baseline (AUD-RM2-DEP-19).
# No host/hostssl/hostnossl/hostgssenc lines: there is no TCP listener (listen_addresses='').
# TYPE  DATABASE          USER            METHOD
local   /^candor_intake_  candor_istore   peer map=candor
local   /^candor_intake_  candor_intake_maint     peer map=maint
local   /^candor_intake_  candor_intake_migrator  peer map=migrate
local   all               all             reject
