# SPDX-License-Identifier: AGPL-3.0-or-later
# Intake cluster client authentication (09 §10 Auth, DB-022, R7 SI-E-01). Installed as
# /etc/candor/intake/postgresql/pg_hba.conf (root:postgres 0640).
# Exactly 09 §10: only the OS user candor-istore, over the Unix socket, as DB role
# candor_istore, to its own tenant database(s); everything else is rejected - including the
# postgres superuser. Bootstrap and migrations run with the service stopped, in single-user
# mode (`postgres --single`), see deploy/SPEC-NOTES.md D-11.
# No host/hostssl/hostnossl/hostgssenc lines: there is no TCP listener (listen_addresses='').
# TYPE  DATABASE          USER            METHOD
local   /^candor_intake_  candor_istore   peer map=candor
local   all               all             reject
