# SPDX-License-Identifier: AGPL-3.0-or-later
# Peer-authentication map (09 §10): OS user candor-istore -> DB role candor_istore only.
# MAPNAME  SYSTEM-USERNAME  PG-USERNAME
candor     candor-istore    candor_istore
