# SPDX-License-Identifier: AGPL-3.0-or-later
# Peer-authentication maps (09 §10, ADR-052(9)): each OS user to exactly one DB role; nothing
# else (compared line by line by config-check, AUD-RM2-DEP-19).
# MAPNAME  SYSTEM-USERNAME  PG-USERNAME
candor     candor-istore    candor_istore
maint      candor-imaint    candor_intake_maint
migrate    candor-migrate   candor_intake_migrator
