# SPDX-License-Identifier: AGPL-3.0-or-later
# Peer-authentication maps (09 §10, ADR-052(9)): OS user candor-istore -> DB role candor_istore,
# OS user candor-migrate -> DB role candor_migrate; nothing else (compared exactly by config-check).
# MAPNAME  SYSTEM-USERNAME  PG-USERNAME
candor     candor-istore    candor_istore
migrate    candor-migrate   candor_migrate
