# SPDX-License-Identifier: AGPL-3.0-or-later
# systemd-coredump on H-INTAKE (20 §11.4 "systemd-coredump masked", REQ-H-58; AUD-RM2-DEP-09).
# Installed as /etc/systemd/coredump.conf.d/50-candor-intake.conf. The installer also masks
# systemd-coredump.socket; kernel.core_pattern=|/bin/false (sysctl.d) keeps the kernel from
# invoking any helper. Belt and braces: even if the helper ran, it would store nothing.
[Coredump]
Storage=none
ProcessSizeMax=0
ExternalSizeMax=0
JournalSizeMax=0
MaxUse=0
KeepFree=0
