// SPDX-License-Identifier: AGPL-3.0-or-later
//! Expected grant matrix (09 §7; `db-grant-audit`). Table-level privileges
//! per role as `SIUD` letters; a role absent from a table's list must hold
//! no table-level privilege. Column-level grants are listed separately.

/// `(schema.table, &[(role, privileges)])`.
pub const TABLE_GRANTS: &[(&str, &[(&str, &str)])] = &[
    ("candor.schema_migration", &[("*", "S")]),
    ("candor.schema_meta", &[("*", "S")]),
    ("candor.column_class", &[("*", "S")]),
    ("core.tenant", &[("*", "S"), ("candor_admin", "SI")]),
    (
        "core.department",
        &[
            ("candor_case", "S"),
            ("candor_relay", "S"),
            ("candor_worker", "S"),
            ("candor_kd", "S"),
            ("candor_auth", "S"),
            ("candor_admin", "SIU"),
        ],
    ),
    (
        "core.channel",
        &[
            ("candor_case", "S"),
            ("candor_relay", "S"),
            ("candor_worker", "S"),
            ("candor_kd", "S"),
            ("candor_auth", "S"),
            ("candor_admin", "SIU"),
        ],
    ),
    (
        "core.channel_member",
        &[
            ("candor_case", "S"),
            ("candor_relay", "S"),
            ("candor_worker", "S"),
            ("candor_kd", "S"),
            ("candor_auth", "S"),
            ("candor_admin", "SIU"),
        ],
    ),
    (
        "core.coi_category",
        &[
            ("candor_case", "S"),
            ("candor_relay", "S"),
            ("candor_worker", "S"),
            ("candor_kd", "S"),
            ("candor_auth", "S"),
            ("candor_admin", "SIU"),
        ],
    ),
    (
        "core.roster_change",
        &[
            ("candor_case", "S"),
            ("candor_relay", "S"),
            ("candor_worker", "S"),
            ("candor_kd", "S"),
            ("candor_auth", "S"),
            ("candor_admin", "SIU"),
        ],
    ),
    (
        "core.retention_policy",
        &[
            ("candor_admin", "SIU"),
            ("candor_case", "S"),
            ("candor_worker", "S"),
        ],
    ),
    (
        "core.workflow_definition",
        &[
            ("candor_admin", "SIU"),
            ("candor_case", "S"),
            ("candor_worker", "S"),
        ],
    ),
    (
        "core.app_user",
        &[
            ("candor_case", "S"),
            ("candor_worker", "S"),
            ("candor_notify", "S"),
            ("candor_kd", "S"),
            ("candor_auth", "S"),
            ("candor_admin", "SIU"),
        ],
    ),
    (
        "core.role",
        &[
            ("candor_case", "S"),
            ("candor_worker", "S"),
            ("candor_notify", "S"),
            ("candor_kd", "S"),
            ("candor_auth", "S"),
            ("candor_admin", "SIU"),
        ],
    ),
    (
        "core.role_assignment",
        &[
            ("candor_case", "S"),
            ("candor_worker", "SD"),
            ("candor_notify", "S"),
            ("candor_kd", "S"),
            ("candor_auth", "S"),
            ("candor_admin", "SIUD"),
        ],
    ),
    (
        "core.permission",
        &[
            ("candor_case", "S"),
            ("candor_admin", "S"),
            ("candor_relay", "S"),
            ("candor_worker", "S"),
            ("candor_notify", "S"),
            ("candor_kd", "S"),
            ("candor_auth", "S"),
        ],
    ),
    (
        "core.coi_registry",
        &[("candor_admin", "SIUD"), ("candor_worker", "S")],
    ),
    (
        "core.import_envelope",
        &[
            ("candor_relay", "I"),
            ("candor_case", "SD"),
            ("candor_worker", "D"),
        ],
    ),
    (
        "core.import_envelope_part",
        &[
            ("candor_relay", "I"),
            ("candor_case", "SD"),
            ("candor_worker", "SUD"),
        ],
    ),
    (
        "core.case",
        &[("candor_case", "SIUD"), ("candor_worker", "D")],
    ),
    (
        "core.submission",
        &[("candor_case", "SIUD"), ("candor_worker", "SUD")],
    ),
    (
        "core.case_member",
        &[("candor_case", "SIUD"), ("candor_worker", "SUD")],
    ),
    (
        "core.case_state_history",
        &[("candor_case", "SIUD"), ("candor_worker", "SUD")],
    ),
    (
        "core.sla_timer",
        &[("candor_case", "SIUD"), ("candor_worker", "SUD")],
    ),
    (
        "core.case_meta",
        &[("candor_case", "SIU"), ("candor_worker", "D")],
    ),
    (
        "core.case_key_wrap",
        &[("candor_case", "SI"), ("candor_worker", "D")],
    ),
    (
        "core.coi_excl_tag",
        &[("candor_case", "I"), ("candor_worker", "D")],
    ),
    (
        "core.case_record",
        &[("candor_case", "SIUD"), ("candor_worker", "D")],
    ),
    (
        "core.message",
        &[("candor_case", "SIUD"), ("candor_worker", "D")],
    ),
    (
        "core.attachment",
        &[("candor_case", "SIUD"), ("candor_worker", "D")],
    ),
    (
        "core.evidence_object",
        &[("candor_case", "SIUD"), ("candor_worker", "D")],
    ),
    (
        "core.evidence_derivative",
        &[("candor_case", "SIUD"), ("candor_worker", "D")],
    ),
    (
        "core.sealed_identity",
        &[("candor_case", "SIUD"), ("candor_worker", "D")],
    ),
    ("core.identity_unseal_request", &[("candor_case", "SIUD")]),
    (
        "core.legal_hold",
        &[("candor_case", "SIU"), ("candor_worker", "D")],
    ),
    (
        "core.deletion_request",
        &[("candor_case", "SIU"), ("candor_worker", "SUD")],
    ),
    (
        "core.wrap_deletion_request",
        &[("candor_case", "SIU"), ("candor_worker", "SUD")],
    ),
    ("core.breakglass_request", &[("candor_case", "SIU")]),
    (
        "core.reply_outbox",
        &[
            ("candor_case", "I"),
            ("candor_relay", "SD"),
            ("candor_worker", "D"),
        ],
    ),
    (
        "core.intake_deletion_list",
        &[("candor_relay", "SI"), ("candor_worker", "SD")],
    ),
    (
        "core.export_package",
        &[("candor_case", "SIUD"), ("candor_worker", "D")],
    ),
    (
        "core.export_approval",
        &[("candor_case", "SIUD"), ("candor_worker", "D")],
    ),
    (
        "core.notification_target",
        &[
            ("candor_case", "SIU"),
            ("candor_notify", "SIUD"),
            ("candor_admin", "S"),
        ],
    ),
    (
        "core.notification_queue",
        &[("candor_notify", "SIUD"), ("candor_worker", "ID")],
    ),
    (
        "core.job",
        &[
            ("candor_case", "I"),
            ("candor_admin", "I"),
            ("candor_relay", "SU"),
            ("candor_notify", "SU"),
            ("candor_kd", "SU"),
            ("candor_auth", "SU"),
            ("candor_worker", "SIUD"),
            ("candor_monitor", "S"),
        ],
    ),
    ("core.config_change", &[("candor_admin", "SIU")]),
    (
        "core.config_bundle",
        &[
            ("candor_admin", "SIU"),
            ("candor_case", "S"),
            ("candor_relay", "S"),
            ("candor_worker", "S"),
            ("candor_notify", "S"),
            ("candor_kd", "S"),
            ("candor_auth", "S"),
        ],
    ),
    (
        "core.idempotency_key",
        &[
            ("candor_case", "SID"),
            ("candor_admin", "SID"),
            ("candor_worker", "D"),
        ],
    ),
    (
        "core.blob_object",
        &[
            ("candor_case", "SIU"),
            ("candor_relay", "SIU"),
            ("candor_worker", "SIUD"),
        ],
    ),
    (
        "core.aggregate_counter",
        &[("candor_worker", "SIU"), ("candor_admin", "S")],
    ),
    ("auth.webauthn_credential", &[("candor_auth", "SIUD")]),
    ("auth.device", &[("candor_auth", "SIUD")]),
    (
        "auth.enrollment_token",
        &[("candor_auth", "SIUD"), ("candor_worker", "D")],
    ),
    (
        "auth.session",
        &[("candor_auth", "SIUD"), ("candor_worker", "D")],
    ),
    (
        "auth.refresh_token",
        &[("candor_auth", "SIUD"), ("candor_worker", "D")],
    ),
    (
        "auth.stepup_proof",
        &[("candor_auth", "SIUD"), ("candor_worker", "D")],
    ),
    (
        "auth.pop_nonce",
        &[("candor_auth", "SIUD"), ("candor_worker", "D")],
    ),
    (
        "kd.kd_entry",
        &[
            ("candor_case", "S"),
            ("candor_admin", "S"),
            ("candor_relay", "S"),
            ("candor_worker", "S"),
            ("candor_kd", "SI"),
            ("candor_auth", "S"),
        ],
    ),
    (
        "kd.kd_checkpoint",
        &[
            ("candor_case", "S"),
            ("candor_admin", "S"),
            ("candor_relay", "S"),
            ("candor_worker", "S"),
            ("candor_kd", "SI"),
            ("candor_auth", "S"),
        ],
    ),
    (
        "kd.witness_cosignature",
        &[
            ("candor_case", "S"),
            ("candor_admin", "S"),
            ("candor_relay", "S"),
            ("candor_worker", "S"),
            ("candor_kd", "SI"),
            ("candor_auth", "S"),
        ],
    ),
    (
        "kd.member_epoch_key",
        &[
            ("candor_case", "S"),
            ("candor_admin", "S"),
            ("candor_relay", "S"),
            ("candor_worker", "S"),
            ("candor_kd", "SI"),
            ("candor_auth", "S"),
        ],
    ),
    (
        "kd.user_key",
        &[
            ("candor_case", "S"),
            ("candor_admin", "S"),
            ("candor_relay", "S"),
            ("candor_worker", "S"),
            ("candor_kd", "SI"),
            ("candor_auth", "S"),
        ],
    ),
    (
        "audit.audit_event",
        &[("candor_audit_w", "SI"), ("candor_audit_r", "S")],
    ),
    (
        "audit.audit_checkpoint",
        &[("candor_audit_w", "SI"), ("candor_audit_r", "S")],
    ),
];

/// Column-level grants `(schema.table, role, privilege letter, columns)`:
/// exactly these columns, no table-level privilege of that kind.
pub const COLUMN_GRANTS: &[(&str, &str, &str, &[&str])] = &[
    (
        "core.tenant",
        "candor_admin",
        "U",
        &["label", "state", "version"],
    ),
    (
        "core.channel_member",
        "candor_kd",
        "U",
        &["state", "version"],
    ),
    (
        "core.roster_change",
        "candor_kd",
        "U",
        &["state", "effective_day"],
    ),
    (
        "core.roster_change",
        "candor_worker",
        "U",
        &["state", "effective_day"],
    ),
    (
        "core.import_envelope",
        "candor_case",
        "U",
        &[
            "state",
            "rejected_by",
            "import_date",
            "header_digest",
            "disposition_ct",
            "escalated_date",
        ],
    ),
    (
        "core.import_envelope",
        "candor_worker",
        "S",
        &[
            "tenant_id",
            "import_envelope_id",
            "channel_id",
            "header_digest",
            "import_date",
            "epoch_index",
            "import_batch_no",
            "state",
            "rejected_by",
            "escalated_date",
        ],
    ),
    (
        "core.import_envelope",
        "candor_worker",
        "U",
        &["state", "header_digest", "escalated_date"],
    ),
    (
        "core.case",
        "candor_worker",
        "S",
        &[
            "tenant_id",
            "case_id",
            "display_ref",
            "channel_id",
            "workflow_def_id",
            "workflow_version",
            "state",
            "priority",
            "received_date",
            "last_import_month",
            "opened_day",
            "closed_day",
            "key_epoch",
            "retention_policy_id",
            "deletion_due_day",
            "legal_hold",
            "ek_missing",
            "version",
        ],
    ),
    (
        "core.case",
        "candor_worker",
        "U",
        &[
            "state",
            "closed_day",
            "deletion_due_day",
            "ek_missing",
            "version",
        ],
    ),
    (
        "core.legal_hold",
        "candor_worker",
        "S",
        &[
            "tenant_id",
            "hold_id",
            "case_id",
            "placed_by",
            "released_by",
            "release_approved_by",
            "placed_day",
            "released_day",
            "version",
        ],
    ),
    (
        "core.breakglass_request",
        "candor_admin",
        "S",
        &[
            "tenant_id",
            "request_id",
            "case_id",
            "requester_id",
            "approver_id",
            "reviewer_id",
            "reason_code",
            "state",
            "expires_at",
            "review_due_day",
            "review_outcome",
            "version",
        ],
    ),
    (
        "core.breakglass_request",
        "candor_worker",
        "S",
        &[
            "tenant_id",
            "request_id",
            "case_id",
            "requester_id",
            "approver_id",
            "reviewer_id",
            "reason_code",
            "state",
            "expires_at",
            "review_due_day",
            "review_outcome",
            "version",
        ],
    ),
    (
        "core.breakglass_request",
        "candor_worker",
        "U",
        &["state", "review_due_day", "version"],
    ),
    ("core.reply_outbox", "candor_relay", "U", &["state"]),
    (
        "core.export_package",
        "candor_worker",
        "S",
        &[
            "tenant_id",
            "export_id",
            "case_id",
            "kind",
            "destination_type",
            "connector_id",
            "blob_id",
            "package_digest",
            "created_by",
            "state",
            "created_day",
        ],
    ),
    (
        "core.export_package",
        "candor_worker",
        "U",
        &["state", "blob_id"],
    ),
    (
        "auth.device",
        "candor_admin",
        "S",
        &["tenant_id", "device_id", "user_id", "state", "enrolled_day"],
    ),
    (
        "auth.device",
        "candor_case",
        "S",
        &["tenant_id", "device_id", "user_id", "state", "enrolled_day"],
    ),
    (
        "auth.webauthn_credential",
        "candor_admin",
        "S",
        &[
            "tenant_id",
            "credential_id",
            "user_id",
            "aaguid",
            "role",
            "created_day",
        ],
    ),
    ("kd.member_epoch_key", "candor_kd", "U", &["state"]),
    ("kd.member_epoch_key", "candor_worker", "U", &["state"]),
    ("kd.user_key", "candor_kd", "U", &["state"]),
    ("audit.audit_event", "candor_audit_w", "U", &["state"]),
];
