# SPDX-License-Identifier: AGPL-3.0-or-later
# Host journal on H-INTAKE (17 §5.5, NET-008, LOG-007, INFRA-016). Installed as
# /etc/systemd/journald.conf.d/50-candor-intake.conf. rsyslog is not installed (17 §5.5).
[Journal]
Storage=volatile
RuntimeMaxUse=64M
MaxRetentionSec=24h
ForwardToSyslog=no
ForwardToKMsg=no
ForwardToConsole=no
ForwardToWall=no
