# SPDX-License-Identifier: AGPL-3.0-or-later
# Host journal on H-INTAKE (17 §5.5, 20 §11.3, NET-008, LOG-007, INFRA-016). Installed as
# /etc/systemd/journald.conf.d/50-candor-intake.conf. rsyslog is not installed (17 §5.5).
# AUD-RM2-DEP-06: no kernel audit records (Audit=no, 20 §11.3); files rotate at least hourly
# (MaxFileSec=1h) so that MaxRetentionSec=24h deletes whole files in time even on a quiet host
# (journald only removes complete files). No level cap: admin SSH/sudo accountability needs
# INFO (20 §11.4); the Candor units suppress their own and PID 1's messages about them with
# LogLevelMax=emerg (SPEC-NOTES D-28).
[Journal]
Storage=volatile
RuntimeMaxUse=64M
MaxRetentionSec=24h
MaxFileSec=1h
Audit=no
ForwardToSyslog=no
ForwardToKMsg=no
ForwardToConsole=no
ForwardToWall=no
