# SPDX-License-Identifier: AGPL-3.0-or-later
# Journal namespace "candor-intake" of tor@candor-intake, candor-intake-web,
# candor-sealer, candor-intake-store and candor-intake-pg (LogNamespace=candor-intake).
# Installed as /etc/systemd/journald@candor-intake.conf.
# NET-008 / LOG-007 / 17 §5.5 / 32 `journald.intake_storage`: volatile, <= 24 h, no
# forwarding of any kind. Kept separate from the host journal so that these units can be
# held to a smaller, shorter store than host/system messages and are never mixed into any
# forwarded stream (ADR-016).
# AUD-RM2-DEP-05: the units discard stdout/stderr (StandardOutput/StandardError=null), so the
# namespace normally stays empty. It still contains any syslog()/journal-socket write of these
# processes (none is expected; AppArmor denies the sockets for the Candor services). It is a
# root-only (plus systemd-journal/adm, which config-check --host requires to be empty),
# volatile store with hourly files and <= 24 h retention, and nothing below `crit` is stored.
[Journal]
Storage=volatile
Compress=yes
Seal=no
SplitMode=none
RuntimeMaxUse=16M
RuntimeMaxFileSize=4M
RuntimeKeepFree=64M
MaxRetentionSec=24h
MaxFileSec=1h
MaxLevelStore=crit
MaxLevelSyslog=emerg
MaxLevelKMsg=emerg
MaxLevelConsole=emerg
MaxLevelWall=emerg
ForwardToSyslog=no
ForwardToKMsg=no
ForwardToConsole=no
ForwardToWall=no
RateLimitIntervalSec=30s
RateLimitBurst=1000
Audit=no
