# SPDX-License-Identifier: AGPL-3.0-or-later
# H-INTAKE has no DNS (17 §4.5, NET-033, INC-33/34): nothing listens on 127.0.0.1:53, so any
# lookup fails locally and no query can leave the host. Installed as /etc/resolv.conf.
nameserver 127.0.0.1
options attempts:1 timeout:1
