# SPDX-License-Identifier: AGPL-3.0-or-later
# CE-SINGLE (18 §4.1): intake VM 10 GiB RAM incl. a 4 GiB Tier W staging tmpfs.
[Mount]
Options=size=4G,nr_inodes=65536,mode=0700,nosuid,nodev,noexec,noswap,X-mount.owner=candor-sealer,X-mount.group=candor-sealer,X-mount.mode=0700
