// SPDX-License-Identifier: Apache-2.0 OR MIT
//! Fixed keys shared by the structure-aware fuzz targets. The committed seeds in
//! `fuzz/seeds/<target>/` are valid under these values; they are generated by
//! `candor-core`'s `vectors::fuzz_seeds` (module `vectors::fuzzkeys`), which must stay
//! in sync with this file (AUD-RM1-CORE-06).
#![allow(dead_code)]

use candor_core::Suite;
use candor_core::hash::{KeyKind, key_id};
use candor_core::kem::{KemKeyPair, KemPublicKey};
use candor_core::slots::SlotContext;
use std::sync::OnceLock;

pub const CK: [u8; 32] = [0x5A; 32];
pub const MEMBER_IKM: [u8; 32] = [0x6B; 32];
pub const TENANT: [u8; 16] = [1; 16];
pub const CHANNEL: [u8; 16] = [2; 16];
pub const EPOCH: u32 = 3;
pub const CASE_ID: [u8; 16] = [4; 16];
pub const VERSION: u32 = 1;
pub const CASE_KEY: [u8; 32] = [0x7C; 32];
pub const EK: [u8; 32] = [0x8D; 32];
pub const OBJECT_HASH: [u8; 32] = [0x9E; 32];
pub const MAILBOX: [u8; 32] = [0xAF; 32];
pub const HPKE_INFO: &[u8] = b"fuzz-info";
pub const HPKE_AAD: &[u8] = b"fuzz-aad";
pub const STREAM_KEY: [u8; 32] = [3; 32];
pub const RECORD_KEY: [u8; 32] = [7; 32];
/// Slot binding of the `fuzz_slot_block/one_member` seed.
pub const SEED_OBJECT_ID: [u8; 16] = [9; 16];
pub const SEED_PAYLOAD_NONCE: [u8; 16] = [8; 16];

pub fn member() -> &'static KemKeyPair {
    static M: OnceLock<KemKeyPair> = OnceLock::new();
    M.get_or_init(|| KemKeyPair::derive(Suite::CandorStd1, &MEMBER_IKM).expect("derive"))
}

pub fn member_ctx() -> SlotContext {
    SlotContext::MemberEpoch { tenant_id: TENANT, channel_id: CHANNEL, epoch_id: EPOCH }
}

/// Key Directory stub containing only the fuzz member (MEK kind).
pub fn directory(kid: &[u8; 32]) -> Option<KemPublicKey> {
    let pk = &member().public;
    (key_id(Suite::CandorStd1, KeyKind::Mek, &pk.to_bytes()) == *kid).then(|| pk.clone())
}
