# SPDX-License-Identifier: AGPL-3.0-or-later
# CE-HARDENED (18 §4.2): H-INTAKE 16 GiB ECC incl. an 8 GiB Tier W staging tmpfs
# (= 32 `intake.tierw_staging_bytes` default).
[Mount]
Options=size=8G,nr_inodes=131072,mode=0700,nosuid,nodev,noexec,noswap,X-mount.owner=candor-sealer,X-mount.group=candor-sealer,X-mount.mode=0700
