#!/usr/bin/env python3
"""Compile specs/REVIEW-REPORT.md from process/REVIEW-{A,B,C}.md and process/DISP-*.md."""
import collections
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
PROC = ROOT / "process"
OUT = ROOT / "specs" / "REVIEW-REPORT.md"

REVIEWERS = {
    "A": ("Reviewer A — adversarial design review from the strongest adversary in the threat model "
          "(state-level network visibility, legal compulsion, supply-chain access)"),
    "B": "Reviewer B — privacy/anonymity researcher (LINDDUN, inference, usable security)",
    "C": "Reviewer C — enterprise/government security architect (procurement, operations, insider/organisation-as-adversary)",
}
RANK = {"Fixed": 0, "Fixed (G1 part)": 1, "Partially fixed": 2, "Accepted residual": 3, "Rejected": 4,
        "Not applicable": 9}


def findings(letter):
    text = (PROC / f"REVIEW-{letter}.md").read_text(encoding="utf-8")
    out = []
    for m in re.finditer(r"^###\s+(RVW-%s-\d+)\s*[—–-]\s*(.+)$" % letter, text, re.M):
        body = text[m.end(): m.end() + 1500]
        sev = re.search(r"SEVERITY:?\**\s*:?\s*\**\s*([A-Za-z]+)", body)
        out.append((m.group(1), m.group(2).strip(), sev.group(1).capitalize() if sev else "?"))
    return out


def norm(disp):
    d = disp.strip().strip("*")
    for k in RANK:
        if d.lower().startswith(k.lower()):
            return k
    if d.lower().startswith("addressed"):
        return "Fixed"
    if d.lower().startswith("accepted"):
        return "Accepted residual"
    return d[:40] or "?"


def dispositions():
    res = collections.defaultdict(list)
    for p in sorted(PROC.glob("DISP-*.md")):
        grp = p.stem.replace("DISP-", "")
        for line in p.read_text(encoding="utf-8").splitlines():
            m = re.match(r"^\|\s*\**(RVW-[ABC]-\d+)\**[^|]*\|\s*([^|]+)\|\s*([^|]*)\|?\s*([^|]*)", line)
            if m:
                res[m.group(1)].append((grp, norm(m.group(2)), m.group(3).strip()[:220], m.group(4).strip()[:160]))
    return res


def main():
    disp = dispositions()
    esc = lambda s: s.replace("|", "\\|")
    lines = ["# REVIEW-REPORT — Adversarial Review and Revision Record", "",
             "Status: GENERATED by `tools/review_report.py` from `process/REVIEW-*.md` and `process/DISP-*.md`. "
             "Regenerate after any disposition change.", "",
             "## 1. Method", "",
             "After the complete v1.0 specification set was written, the lead architect switched roles and commissioned three "
             "independent adversarial reviews, each instructed to break the design from a different perspective. Each weakness "
             "was recorded with scenario, affected documents, why the spec did not prevent it, a proposed fix and residual risk "
             "(full text in `process/REVIEW-A.md`, `REVIEW-B.md`, `REVIEW-C.md`). The lead architect then issued binding revision "
             "decisions ADR-034..ADR-047 (`DECISIONS.md` §7) and eight revision groups (G1–G8) plus a final consistency pass "
             "(F1–F3) amended every affected document, recording a disposition for every finding that touched their documents "
             "(`process/DISP-*.md`). Where a reviewer's proposed fix conflicted with a revision ADR, the ADR prevailed and the "
             "difference is noted in the disposition.", "",
             "Final status per finding = the WEAKEST disposition recorded by any group whose documents it touched (a finding is Fixed only when every affected document fixed its part), with all group dispositions listed. "
             "'Partially fixed' means the design change landed but a documented residual risk remains (see the affected "
             "document's Residual risks section and `40-SECURITY-ASSUMPTIONS.md`).", ""]
    summary = []
    table = []
    for letter, desc in REVIEWERS.items():
        fs = findings(letter)
        sev = collections.Counter(f[2] for f in fs)
        status = collections.Counter()
        rows = []
        for fid, title, s in fs:
            ds = [d for d in disp.get(fid, []) if d[1] != "Not applicable"]
            best = max((d[1] for d in ds), key=lambda x: RANK.get(x, 5), default="UNADDRESSED")
            best = "Fixed" if best == "Fixed (G1 part)" else best
            status[best] += 1
            where = "; ".join(f"{g}: {d}" for g, d, _, _ in ds) or "—"
            changes = " · ".join(f"[{g}] {c}" for g, _, c, _ in ds if c)[:600]
            rows.append(f"| {fid} | {esc(title)[:140]} | {s} | **{best}** | {esc(where)} | {esc(changes)} |")
        summary.append(f"| {letter} | {desc} | {len(fs)} | "
                       + ", ".join(f"{k} {v}" for k, v in sorted(sev.items())) + " | "
                       + ", ".join(f"{k} {v}" for k, v in sorted(status.items(), key=lambda kv: RANK.get(kv[0], 5))) + " |")
        table.append(f"\n## {len(table) + 3}. Findings — Reviewer {letter}\n")
        table.append("| Finding | Title | Severity | Final status | Dispositions by group | Changes (abridged) |")
        table.append("|---|---|---|---|---|---|")
        table.extend(rows)
    lines += ["## 2. Summary", "", "| Reviewer | Perspective | Findings | By severity | By final status |",
              "|---|---|---|---|---|"] + summary
    lines += ["", "Revision decisions: ADR-034 (Tier W RAM-only drafts), ADR-035 (intake integrity evidence: external "
              "watchers, operator statement, optional confidential-VM sealer, independent approval of intake captures), "
              "ADR-036 (key-directory governance), ADR-037 (triage-first routing, blinded COI state), ADR-038 (fixed-schedule "
              "imports and constant-schedule notifications), ADR-039 (fetch-all reply retrieval), ADR-040 (platform package "
              "manifest, security floors), ADR-041 (client acquisition), ADR-042 (Desk platform containment), ADR-043 "
              "(independent-custody devices), ADR-044 (key-access continuity and records obligations), ADR-045 "
              "(organisation-as-adversary controls), ADR-046 (consistency and parameter fixes), ADR-047 (chaff envelopes, "
              "metadata erasure, freshness bounds and other final decisions)."]
    lines += table
    lines += ["", f"## {len(REVIEWERS) + 3}. Residual weaknesses that remain after revision", "",
              "Findings not marked Fixed are listed above with their residual risk in the group dispositions. The "
              "structurally irreducible residuals are:",
              "",
              "1. A live-compromised or compelled intake server can capture Tier W (no-JavaScript) plaintext and passphrases "
              "at login; mitigated by detection (watchers, operator statements, optional TEE) and by recommending Tier V "
              "for high-risk sources — not prevented.",
              "2. An organisation that controls a recipient's endpoint can defeat Desk protections; mitigated by "
              "independent-custody devices for INDEPENDENT channels — a policy/procurement control, not a technical guarantee.",
              "3. Network-level correlation of Tor use by an employer/ISP, stylometry, document canary traps and "
              "content-based identification are outside what the platform can prevent; addressed by source guidance (05), "
              "delayed delivery and coarse timestamps.",
              "4. Tor onion circuits use classical key exchange today; recorded Tier W sessions face harvest-now-decrypt-later "
              "risk until Tor deploys post-quantum handshakes.",
              "5. Deletion reaches backups only within the Erasure Key Vault backup window (≤14 days) and only if "
              "infrastructure-level backups exclude the vault volume.", ""]
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
