#!/usr/bin/env python3
"""Generate specs/39-REQUIREMENTS-TRACEABILITY.md and validate requirement hygiene.

Parses every requirement row of the form
  | ID | Requirement | Evidence | Threats | Component | Verification |
from specs/*.md and emits the traceability matrix plus a lint report.
Exit code 1 if any ERROR-level lint finding exists.
"""
import collections
import pathlib
import re
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import constants_lint  # noqa: E402  (ADR-047(11): canonical constants registry + SG-25 lint)

ROOT = pathlib.Path(__file__).resolve().parent.parent
SPECS = ROOT / "specs"
OUT = SPECS / "39-REQUIREMENTS-TRACEABILITY.md"

ID_RE = re.compile(r"^[A-Z][A-Z0-9]{1,6}-\d{3}[a-z]?$")
THR_RE = re.compile(r"THR-\d{3}")
COMP_RE = re.compile(r"C-\d{2}")
EVID_RE = re.compile(r"(B-[A-Z]{2,3}-\d{2,3}|INC-\d{2,3}|F-\d{3}|ADR-\d{3}|REQ-H-\d{2,3}b?)")
TEST_RE = re.compile(r"\b(ST-\d{3}|AT-\d{3})\b")
# Prefixes whose rows are catalog entries rather than requirements.
NON_REQ = {"THR", "ADV", "ST", "AT", "F", "INC", "ADR", "RVW"}
SEC_HINT = re.compile(r"(?i)encrypt|key|log|auth|anonym|metadata|tor|sign|audit|secur|privacy|delete|erase|source")


def split_row(line):
    cells = [c.strip() for c in line.strip().strip("|").split("|")]
    return cells


def parse():
    reqs = []
    catalog = collections.defaultdict(set)  # ids defined as catalog rows (THR, ST, AT, ...)
    for path in sorted(SPECS.glob("*.md")):
        if path.name in (OUT.name, "DECISIONS.md"):
            continue
        for lineno, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
            if not line.startswith("|"):
                continue
            cells = split_row(line)
            if not cells or not ID_RE.match(cells[0].strip("*` ")):
                continue
            rid = cells[0].strip("*` ")
            prefix = rid.split("-")[0]
            if prefix in NON_REQ:
                catalog[prefix].add(rid)
                continue
            if len(cells) < 6:
                continue
            reqs.append({
                "id": rid, "doc": path.name, "line": lineno,
                "text": cells[1], "evidence": cells[2], "threats": cells[3],
                "component": cells[4], "verification": cells[5],
            })
    return reqs, catalog


def lint(reqs, catalog):
    findings = []
    seen = {}
    for r in reqs:
        where = f"{r['doc']}:{r['line']}"
        if r["id"] in seen:
            findings.append(("ERROR", r["id"], f"duplicate ID (also {seen[r['id']]})", where))
        else:
            seen[r["id"]] = where
        v = r["verification"].strip()
        if not v or v in {"—", "-", "TBD", "N/A"}:
            sev = "ERROR" if SEC_HINT.search(r["text"]) else "WARN"
            findings.append((sev, r["id"], "no verification strategy", where))
        if not r["evidence"].strip() or r["evidence"].strip() in {"—", "-"}:
            findings.append(("WARN", r["id"], "no evidence cited", where))
        for t in TEST_RE.findall(v):
            pre = t.split("-")[0]
            if catalog.get(pre) and t not in catalog[pre]:
                findings.append(("WARN", r["id"], f"references undefined test {t}", where))
        for t in THR_RE.findall(r["threats"]):
            if catalog.get("THR") and t not in catalog["THR"]:
                findings.append(("WARN", r["id"], f"references undefined threat {t}", where))
    return findings


def main():
    reqs, catalog = parse()
    findings = lint(reqs, catalog)
    by_doc = collections.Counter(r["doc"] for r in reqs)
    thr_cov = collections.defaultdict(list)
    for r in reqs:
        for t in set(THR_RE.findall(r["threats"])):
            thr_cov[t].append(r["id"])
    esc = lambda s: s.replace("|", "\\|")
    out = []
    out.append("# 39 — Requirements Traceability Matrix\n")
    out.append("Status: GENERATED by `tools/traceability.py` — do not edit by hand. "
               "Regenerate after any specification change: `python3 tools/traceability.py`.\n")
    out.append("## 1. Purpose\n\nLinks every requirement: RESEARCH/FINDING (Evidence) → THREAT → REQUIREMENT → "
               "IMPLEMENTATION COMPONENT → TEST/VERIFICATION → DOCUMENTATION (defining spec file). "
               "The generator also lints the set: duplicate IDs, missing verification on security requirements "
               "(ERROR, release-blocking per 27-SECURE-DEVELOPMENT.md), missing evidence, dangling test/threat references.\n")
    out.append("## 2. Summary\n")
    out.append(f"- Requirements: **{len(reqs)}** across **{len(by_doc)}** documents")
    out.append(f"- Threats defined: {len(catalog.get('THR', []))}; threats referenced by ≥1 requirement: {len(thr_cov)}")
    out.append(f"- Security tests defined (ST-): {len(catalog.get('ST', []))}; anonymity tests defined (AT-): {len(catalog.get('AT', []))}")
    errs = sum(1 for f in findings if f[0] == "ERROR")
    out.append(f"- Lint: {errs} ERROR, {len(findings) - errs} WARN\n")
    out.append("| Document | Requirements |\n|---|---|")
    for d, n in sorted(by_doc.items()):
        out.append(f"| {d} | {n} |")
    out.append("\n## 3. Threat coverage (THR → requirements)\n")
    out.append("| Threat | # | Requirements |\n|---|---|---|")
    for t in sorted(catalog.get("THR", set()) | set(thr_cov)):
        ids = thr_cov.get(t, [])
        out.append(f"| {t} | {len(ids)} | {', '.join(ids) if ids else '**UNCOVERED**'} |")
    out.append("\n## 4. Matrix\n")
    out.append("| Requirement | Evidence (research/finding) | Threats | Component | Verification (test) | Documentation |")
    out.append("|---|---|---|---|---|---|")
    for r in reqs:
        out.append(f"| {r['id']} | {esc(r['evidence'])} | {esc(r['threats'])} | {esc(r['component'])} | "
                   f"{esc(r['verification'])} | {r['doc']} |")
    out.append("\n## 5. Lint findings\n")
    if findings:
        out.append("| Severity | ID | Finding | Location |\n|---|---|---|---|")
        for f in findings:
            out.append(f"| {f[0]} | {f[1]} | {esc(f[2])} | {f[3]} |")
    else:
        out.append("None.")
    registry = constants_lint.load_registry()
    c_conf, c_style, c_missing = constants_lint.run_lint(registry)
    out.append("\n## 6. Canonical constants registry\n")
    out.append("Owned by this document per ADR-047(11). Source: `tools/constants.json` "
               "(machine-readable; entries carry conflict and required patterns). Specifications reference "
               "these values and SHALL NOT restate divergent literals.\n")
    out.append(constants_lint.registry_markdown(registry))
    out.append("\n## 7. Constants lint\n")
    out.append("Spec-constant consistency lint (`tools/constants_lint.py`; ST-167, SG-25). ERROR = a literal in "
               "`specs/*.md` conflicting with the registry; WARN = same value in a divergent unit/spelling, or the "
               "owner document no longer states the canonical value. History lines (withdrawn/superseded/v1.0) "
               "are skipped.\n")
    out.append(constants_lint.lint_markdown(c_conf, c_style, c_missing))
    OUT.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"{len(reqs)} requirements, {errs} errors, {len(findings) - errs} warnings; "
          f"constants lint: {len(c_conf)} conflicts -> {OUT.relative_to(ROOT)}")
    return 1 if errs else 0


if __name__ == "__main__":
    sys.exit(main())
